### ISSUE TITLE
Dying Light 2 HUD Fix

### ISSUE THREAD

**Issue by metalheadbangg** [P4TOLINO06/FSR3.0-Mod-Setup-Utility#4]
After following the guide for Dying Light 2 in the Utility, do not enable FG when starting the game. Go to HUD settings, turn off all HUD elements and start the game. Then go back to settings and enable FG and the Upscaler method that suits you, DLSS(FSR3) or FSR2 doesn't matter. Continue the game and go back to HUD Settings and enable the elements you want. You need to do this every time you start the game.

**Comment by P4TOLINO06** [comment]
The dl2 mods are experiencing bugs after some game updates. A new mod will
be added in the next updates.

Em ter., 16 de jul. de 2024 às 20:16, metalheadbangg <
***@***.***> escreveu:

**Comment by metalheadbangg** [comment]
Thanks for creating this amazing tool by the way. Just wanted to contribute but i couldn't label this post documentation or enhancement. I don't actually use github as you can see. If you say newer method will permanently fix that, then there's no need additional guide info. Thanks!

**Comment by metalheadbangg** [comment]
Just tried optiscaler mod and fg works fine like the 0.10.3. I temporarily fixed the HUD with the method i wroted above. You can add DL2 guide also. Just works perfect. I don't think mods will fix this permanently without modders try it specifically for this game. But turning off the HUD and changing the upscaling option works solid. Maybe this trick might work for other games too.

**Comment by P4TOLINO06** [comment]
The optiscaler works perfectly in tw3 as well. I think it was the mod with
the best graphical quality I've tested. But it's not just the optiscaler;
there are some other files included. I will add it to more games in the
next updates

Em ter., 16 de jul. de 2024 às 21:07, metalheadbangg <
***@***.***> escreveu:
