### ISSUE TITLE
after use fsr3.1 Black Myth Wukong has bug

### ISSUE THREAD

**Issue by whitedustmoon1175** [P4TOLINO06/FSR3.0-Mod-Setup-Utility#5]
After install the fsr mod, there're blue blocks on snowfield in black myth wukong.

**Comment by whitedustmoon1175** [comment]
My graphics cards is AMD RX 7900GRE

**Comment by P4TOLINO06** [comment]
This is an issue with the fsr3 mod itself, I don't think there's a fix,
also, don't use the 0.7.6 mods, etc., and uniscaler they don't work in
black myth

Em qua., 28 de ago. de 2024 às 00:15, whitedustmoon1175 <
***@***.***> escreveu:

**Comment by whitedustmoon1175** [comment]
thank for your help

**Comment by P4TOLINO06** [comment]
You can try to fix it by using Xess as the upscaler in the mod menu within
the game,  just press the Insert key to open the mod.
If the menu doesn't open, you can set the upscaler to Upscaler Optiscaler
and install it in the same folder along with the FSR 3.1/DLSS Optiscaler
mod

Em qua., 28 de ago. de 2024 às 00:41, whitedustmoon1175 <
***@***.***> escreveu:
